version: '3.8'

# Production Application Tier
# Deploy this on 2-3 application servers with load balancer

x-common-config: &common-config
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"
      max-file: "5"

services:
  # API Gateway - Production
  api-gateway:
    build:
      context: ../../
      dockerfile: docker/production-images/api-gateway.Dockerfile
    image: collectioncrm/api-gateway:${APP_VERSION:-latest}
    <<: *common-config
    env_file:
      - ../../src/services/api-gateway/.env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - INSTANCE_ID=${HOSTNAME:-app-server-1}
    expose:
      - "3000"
    depends_on:
      - auth-service
      - bank-sync-service
      - workflow-service
    networks:
      - collectioncrm-app-network
      - collectioncrm-external-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  # Authentication Service - Production
  auth-service:
    build:
      context: ../../
      dockerfile: docker/production-images/auth-service.Dockerfile
    image: collectioncrm/auth-service:${APP_VERSION:-latest}
    <<: *common-config
    env_file:
      - ../../src/services/auth-service/.env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - INSTANCE_ID=${HOSTNAME:-app-server-1}
    expose:
      - "3000"
    networks:
      - collectioncrm-app-network
      - collectioncrm-external-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  # Bank Synchronization Service - Production
  bank-sync-service:
    build:
      context: ../../
      dockerfile: docker/production-images/bank-sync-service.Dockerfile
    image: collectioncrm/bank-sync-service:${APP_VERSION:-latest}
    <<: *common-config
    env_file:
      - ../../src/services/bank-sync-service/.env.production
    environment:
      - NODE_ENV=production
      - PORT=3002
      - INSTANCE_ID=${HOSTNAME:-app-server-1}
    expose:
      - "3002"
    networks:
      - collectioncrm-app-network
      - collectioncrm-external-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  # Workflow Service - Production
  workflow-service:
    build:
      context: ../../
      dockerfile: docker/production-images/workflow-service.Dockerfile
    image: collectioncrm/workflow-service:${APP_VERSION:-latest}
    <<: *common-config
    env_file:
      - ../../src/services/workflow-service/.env.production
    environment:
      - NODE_ENV=production
      - PORT=3003
      - INSTANCE_ID=${HOSTNAME:-app-server-1}
    expose:
      - "3003"
    networks:
      - collectioncrm-app-network
      - collectioncrm-external-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  # Campaign Engine Service - Production
  campaign-engine:
    image: collectioncrm/campaign-engine:${APP_VERSION:-latest}
    <<: *common-config
    env_file:
      - ../../src/services/campaign-engine/.env.production
    environment:
      - NODE_ENV=production
      - PORT=3004
      - INSTANCE_ID=${HOSTNAME:-app-server-1}
    expose:
      - "3004"
    networks:
      - collectioncrm-app-network
      - collectioncrm-external-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  # Payment Service - Production
  payment-service:
    image: collectioncrm/payment-service:${APP_VERSION:-latest}
    <<: *common-config
    env_file:
      - ../../src/services/payment-service/.env.production
    environment:
      - NODE_ENV=production
      - PORT=3005
      - INSTANCE_ID=${HOSTNAME:-app-server-1}
    expose:
      - "3005"
    networks:
      - collectioncrm-app-network
      - collectioncrm-external-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  collectioncrm-app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
  collectioncrm-external-network:
    external: true
    name: collectioncrm-external