global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000']

  - job_name: 'bank-sync-service'
    static_configs:
      - targets: ['bank-sync-service:3000']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3000']

  - job_name: 'workflow-service'
    static_configs:
      - targets: ['workflow-service:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']