name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docker/base-images/**'
      - '.github/workflows/docker-build-push.yml'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-push-api-gateway:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/collectioncrm/api-gateway
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,format=short

      - name: Build and push API Gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./src/services/api-gateway
          file: ./docker/base-images/node.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-auth-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/collectioncrm/auth-service
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,format=short

      - name: Build and push Auth Service image
        uses: docker/build-push-action@v4
        with:
          context: ./src/services/auth-service
          file: ./docker/base-images/node.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Additional jobs for other services can be added following the same pattern
  # For brevity, only two services are included in this example